### ISSUE TITLE
missing pidclient.jar dependency

### ISSUE THREAD

**Issue by mmkrystek** [VITObelgium/snap-spark#9]
Hello, 
I'm trying to build snap-spark project.
snap-bundle module builds successfully, however snap-gpt-spark fails on resolving dependency to be.vito.eodata:pidclient:jar:jar-with-dependencies:0.1.9
Where can I find this jar? Is seems that it is not available in https://repo.maven.apache.org/maven2. I can not find any source code project for this jar either.

**Comment by jdries** [comment]
That dependency indeed seems to be internal. Could you perhaps try removing it from the pom file? If I remember correctly, we tried to make it optional.
For a public version of the jar itself, you could look here:
https://artifactory.vgt.vito.be/webapp/#/artifacts/browse/simple/General/libs-release-public/be/vito/eodata/snap-gpt-spark/1.2.0/snap-gpt-spark-1.2.0.jar

**Comment by mmkrystek** [comment]
There are direct imports of be.vito.pidclient package in
https://github.com/VITObelgium/snap-spark/blob/master/snap-gpt-spark/src/main/java/be/vito/terrascope/snapgpt/ProcessFilesGPT.java
Classes are used in the source code, so removing dependency is not an option. Unless these classes can be safely removed from the source?

**Comment by jdries** [comment]
I pushed some changes of the last months into this repo, which also removes the dependency on pidclient.
Also upgraded to snap 8.x.
So issue should be resolved!
